version: '3.7'
services:
  app:
    image: skep/app
    networks:
      - skep
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      SKEP_SECRET:
      SKEP_CALCULATOR_URL: http://calculator:8080/

  agent:
    image: skep/agent
    networks:
      - skep
    deploy:
      mode: global
    volumes:
      - "/dev:/hostfs/dev:ro"
      - "/etc:/hostfs/etc:ro"
      - "/proc:/hostfs/proc:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      SKEP_SECRET:
      SKEP_APP_URL: http://app:8080
      SKEP_CALCULATOR_URL: http://calculator:8080/
      DISKS:
      FILE_SYSTEMS:
      NETWORK_INTERFACES:
      COLLECT_INTERVAL:
      SAMPLE_DURATION:
      LOG_LEVEL:
      SKEP_HOST:

  calculator:
    image: skep/calculator
    networks:
      - skep
    deploy:
      mode: replicated
      replicas: 1
    environment:
      SKEP_SECRET:
      SKEP_APP_URL: http://app:8080
      LOG_LEVEL:

  monitor:
    image: skep/monitor
    networks:
      - skep
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      SKEP_SECRET:
      SKEP_APP_URL: http://app:8080
      SKEP_CALCULATOR_URL: http://calculator:8080/
      SERVICE_URL_TEMPLATE:
      IMAGE_URL_TEMPLATE: https://hub.docker.com/r/{organization}/{repository}

networks:
  skep: {}
