version: '3.7'
services:
  app:
    image: skep/app
    networks:
      - skep
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./app:/skep:rw"

  stats:
    image: skep/stats
    volumes:
      - "/proc:/hostfs/proc:ro"
      - "/etc:/hostfs/etc:ro"
    environment:
      SKEP_APP_URL: http://host.docker.internal:5000
      SKEP_HOST:
      LINUX_METRICS_ROOT_FS: '/hostfs'
      DISK_DRIVES: 'sda:sda1'
      NETWORK_INTERFACES: 'eth0'
      LOG_LEVEL: 'DEBUG'

    networks:
      - skep

networks:
  skep: {}
