version: '3.7'
services:
  app:
    image: skep/app
    networks:
      - skep
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      mode: replicated
      replicas: 1

  stats:
    image: skep/stats
    volumes:
      - "/dev:/hostfs/dev:ro"
      - "/etc:/hostfs/etc:ro"
      - "/proc:/hostfs/proc:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      SKEP_APP_URL: http://app:8080
      SKEP_HOST:
      DISKS: 'sda1'
      FILE_SYSTEMS: '/'
      NETWORK_INTERFACES: 'eth0'
      LOG_LEVEL: 'INFO'

    networks:
      - skep

    deploy:
      mode: global

networks:
  skep: {}
