version: '3.7'
services:
  skep:
    image: skep/app
    networks:
      - skep
    ports:
      - "8080:8080"

  stats:
    image: skep/stats
    volumes:
      - "/proc:/hostfs/proc:ro"
    environment:
      SKEP_HOST_URL: http://skep:8080
      LINUX_METRICS_ROOT_FS: '/hostfs'
      DISK_DRIVES: 'sda:sda1'
      NETWORK_INTERFACES: 'eth0'
      LOG_LEVEL: 'DEBUG'

    networks:
      - skep

networks:
  skep: {}
